name:  Flutter

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        
jobs:
    build:
        runs-on : ubuntu-latest

        steps:
            - name: Get Repo
              uses: actions/checkout@v3
            
            - name: Get Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: "3.10.1"
                channel: "stable"
            
            - name: check version
              run: |
                flutter --version
            - name: install dependencies
              run: |
                flutter pub get
            - name: running test
              run: |
                flutter test
            


